num = input("Посчитаем сумму и произведение трёхзначного числа.")
num = input("Введите трёхзначное число: ")
num = int(num)
a = num // 100
b = num % 100 // 10
c = num % 10
summa = a + b +c
mult = a * b *c
print(f'Сумма = {summa}')
print(f'Произведение = {mult}')